// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-wedding-details.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var schedule = [
  {
    title: "Engagement Day",
    date: "12.09.2026",
    weekday: "Saturday",
    events: [
      { name: "Engagement Ceremony (Nichayathartham)", time: "7:30 AM \u2013 9:00 AM" },
      { name: "Exchange of Ceremonial Gifts (Murai Vazhi Seer)", time: "10:30 AM \u2013 1:00 PM" },
      { name: "Muhurtha Kaal (Ceremonial Ritual)", time: "After 5:30 PM" },
      { name: "Reception", time: "After 6:00 PM" }
    ]
  },
  {
    title: "Wedding Day",
    date: "13.09.2026",
    weekday: "Sunday",
    events: [
      { name: "Wedding Muhurtham", time: "Between 6:30 AM and 7:30 AM" },
      { name: "Wedding Lunch (Sambandhi Virundhu)", time: "After 12:00 PM" }
    ]
  }
];
var details = {
  couple: { bride: "Samyuktha", groom: "Saran" },
  weddingDate: "2026-09-13",
  weddingTime: "6:30 AM (Muhurtham between 6:30 AM and 7:30 AM)",
  venue: {
    name: "Suguna Auditorium",
    area: "Sitra",
    directions: "https://maps.app.goo.gl/MPNAbGj9Dv4uHpUC8"
  },
  schedule
};
var get_wedding_details_default = defineTool({
  name: "get_wedding_details",
  title: "Get wedding details",
  description: "Get the couple's names, wedding date and time, venue with directions link, and the full ceremony schedule.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(details, null, 2) }],
    structuredContent: details
  })
});

// src/lib/mcp/tools/list-guest-wishes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-guest-wishes.ts
var list_guest_wishes_default = defineTool2({
  name: "list_guest_wishes",
  title: "List guest wishes",
  description: "List the public guest wishes posted on the wedding invitation site, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many wishes to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("guest_wishes").select("id, guest_name, message, is_anonymous, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const wishes = (data ?? []).map((w) => ({
      id: w.id,
      name: w.is_anonymous ? "Anonymous Guest" : w.guest_name,
      message: w.message,
      created_at: w.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(wishes, null, 2) }],
      structuredContent: { wishes }
    };
  }
});

// src/lib/mcp/tools/post-guest-wish.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var post_guest_wish_default = defineTool3({
  name: "post_guest_wish",
  title: "Post a guest wish",
  description: "Post a short public wish or blessing for the couple on the wedding invitation site.",
  inputSchema: {
    guest_name: z2.string().trim().min(1).max(80).describe("Name of the guest posting the wish."),
    message: z2.string().trim().min(1).max(500).describe("The wish message."),
    is_anonymous: z2.boolean().default(false).describe("When true, the wish is shown as posted by 'Anonymous Guest'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ guest_name, message, is_anonymous }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("guest_wishes").insert({ guest_name, message, is_anonymous: is_anonymous ?? false }).select("id, guest_name, message, is_anonymous, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wish posted: ${JSON.stringify(data)}` }],
      structuredContent: { wish: data }
    };
  }
});

// src/lib/mcp/tools/submit-rsvp.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var submit_rsvp_default = defineTool4({
  name: "submit_rsvp",
  title: "Submit an RSVP",
  description: "Submit an RSVP for the wedding with the number of guests attending (1-10).",
  inputSchema: {
    guest_count: z3.number().int().min(1).max(10).describe("Number of guests attending.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ guest_count }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("rsvps").insert({ guest_count }).select("id, guest_count, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `RSVP recorded for ${guest_count} guest(s).` }],
      structuredContent: { rsvp: data }
    };
  }
});

// src/lib/mcp/tools/get-rsvp-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_rsvp_summary_default = defineTool5({
  name: "get_rsvp_summary",
  title: "Get RSVP summary",
  description: "Get the total number of RSVP submissions and the total guests confirmed so far.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("rsvps").select("guest_count");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const summary = {
      submissions: data?.length ?? 0,
      total_guests: (data ?? []).reduce((sum, r) => sum + (r.guest_count ?? 0), 0)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "everlasting-vows",
  title: "Everlasting Vows",
  version: "0.1.0",
  instructions: "Tools for the Saran & Samyuktha wedding invitation site. Use `get_wedding_details` for the date, venue and ceremony schedule, `list_guest_wishes` / `post_guest_wish` for public guest blessings, and `submit_rsvp` / `get_rsvp_summary` for attendance.",
  tools: [get_wedding_details_default, list_guest_wishes_default, post_guest_wish_default, submit_rsvp_default, get_rsvp_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
